[package]
name = "tuser_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = {workspace = true}
ratatui = {workspace = true}
crossterm = {workspace = true}
tokio = {workspace = true}
