name: "Roob's Kitchen App"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [windows-latest,macos-latest,ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: cargo build --verbose
    - name: Unit Test
      run: cargo test --verbose
